### ISSUE TITLE
Plugin disables itself periodically

### ISSUE THREAD

**Issue by C-Duv** [fusioninventory/fusioninventory-for-glpi#2111]
The past few days I've noticed the plugin was not enabled (FusionInventory-specific informations were missing on a Computer object).
First I thought I had disabled it by mistake without noticing but after a few days it got disabled again: So I'm pretty sure it disables itself.

In the plugin list, I have the *Upgrade* button, after I clicked it I get the *Enable*.

Since I run *Upgrade*, I also run into #1894, but that's another topic.

Can't find any "Plugin disabled" event in the GLPI logs: is there any?

Versions:
GLPI v9.1.2
FusionInventory plugin v9.1+1.1

**Comment by ddurieux** [comment]
It can be a problem with php-cli not have right module, or a problem with backup....
We have removed this code and will be available for the next version

**Comment by C-Duv** [comment]
Can you point me towards the updated code so that I test it on my side?

**Comment by C-Duv** [comment]
Workaround (in my case):

1. Apply commit 776505be5d4e0122e098dd28abebbd494d13536e
2. Run the following queries:
   ```SQL
   UPDATE `glpi_plugin_fusioninventory_configs` SET `value` = '9.1+1.1' WHERE `type` = 'version';
   UPDATE `glpi_plugins` SET `state`=1 WHERE `directory`= 'fusioninventory';
   ```
3. Logout and re-log to GLPI: plugin should be enabled and working

**Comment by trasher** [comment]
Fixed as of https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2060

**Comment by ftoledo** [comment]
wich this patch and the sql updates i still have this issue on glpi 9.1.6 and fusioninventory 9.1+1.1
