### ISSUE TITLE
misspelled task variable in last fusioninventory plugin

### ISSUE THREAD

**Issue by cadegenn** [fusioninventory/fusioninventory-for-glpi#2792]
Hi,

variable `tasks` is misspelled `taks` in file `inc/agentwakeup.class.php`

```
169c169
<                'glpi_plugin_fusioninventory_tasks.id'             => $taks['id'],
---
>                'glpi_plugin_fusioninventory_tasks.id'             => $tasks['id'],
```

Maybe it can resolve issues #2789  #2790 and #2791 because it just filled up my hard drive in `php-errors.log` too.

Thank you

**Comment by trasher** [comment]
Fixed as of https://github.com/fusioninventory/fusioninventory-for-glpi/commit/db945f3f4d14821d3d95e11d2a00e0ff9e14e4d6

**Comment by adamcios** [comment]
i change this line from taks  to task and then from task to tasks and nothing change. i still have problem with php-errors.....

[2019-04-03 08:33:42] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/www/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): preg_match_all(): Compilation failed: nothing to repeat at offset 1
  Backtrace :
  :
  inc/rulecriteria.class.php:452                     preg_match_all()
  inc/rule.class.php:1612                            RuleCriteria::match()
  inc/rule.class.php:1553                            Rule->checkCriteria()
  inc/rule.class.php:1429                            Rule->checkCriterias()
  inc/rulecollection.class.php:1539                  Rule->process()
  inc/software.class.php:140                         RuleCollection->processAllRules()
  inc/commondbtm.class.php:1100                      Software->prepareInputForAdd()
  ...ventory/inc/inventorycomputerlib.class.php:2370 CommonDBTM->add()
  ...ventory/inc/inventorycomputerlib.class.php:2894 PluginFusioninventoryInventoryComputerLib->addSoftware()
  ...nventory/inc/inventorycomputerlib.class.php:916 PluginFusioninventoryInventoryComputerLib->importSoftware()
  ...ry/inc/inventorycomputerinventory.class.php:537 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:769 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1432                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1539                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:337 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:229 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"199@glpi"}
