### ISSUE TITLE
Deploy function and Remote inventory.

### ISSUE THREAD

**Issue by Sergh71** [fusioninventory/fusioninventory-for-glpi#3082]
Hello.
Please, help.
Found 2 bugs.
GLPI 9.5.3
FusionInventory 9.5.0 + 1.0
1) Remote inventory from the server does not work. The process is constantly running, but nothing happens.
![Remote inventory](https://user-images.githubusercontent.com/77730253/105172267-69695280-5b30-11eb-8ce6-45311b608385.jpg)

2) 2. The "Deploy" function does not work.
The task weighs in the "Prepared" status. I initiate the connection from the host. Inventory data comes in, but "Deploy" is not executed and is in the "Prepared" status.
![Deploy](https://user-images.githubusercontent.com/77730253/105172347-8b62d500-5b30-11eb-9b8e-9ce5a7d39508.jpg)

Before that I worked in FusionInventory 9.4 + 2.4 and there were no such problems. "Delploy" and remote inventory from the server worked. Please, help.

**Comment by Sergh71** [comment]
Log from agent

[Wed Jan 20 15:08:21 2021][info] FusionInventory Agent memory usage: WSS=3244032 PFU=148402176
[Wed Jan 20 15:10:06 2021][info] running task Maintenance
[Wed Jan 20 15:10:10 2021][info] FusionInventory Agent memory usage: WSS=3194880 PFU=144474112
[Wed Jan 20 15:10:12 2021][info] target server0: server https://172.16.104.223/plugins/fusioninventory
[Wed Jan 20 15:10:12 2021][info] sending prolog request to server0
[Wed Jan 20 15:10:21 2021][info] running task Inventory
[Wed Jan 20 15:10:21 2021][info] New inventory from ws3.tech.local-2021-01-20-12-47-03 for server0
[Wed Jan 20 15:11:48 2021][info] running task Collect
[Wed Jan 20 15:11:48 2021][info] No Collect job enabled or Collect support disabled server side.
[Wed Jan 20 15:11:52 2021][info] running task Deploy
[Wed Jan 20 15:11:53 2021][error] [http client] Can't decode JSON content, starting with <!DOCTYPE html>
[Wed Jan 20 15:11:53 2021][info] No Deploy job found in server jobs list.
[Wed Jan 20 15:12:01 2021][info] running task ESX
[Wed Jan 20 15:12:01 2021][info] No ESX job enabled or ESX support disabled server side.
[Wed Jan 20 15:12:05 2021][info] FusionInventory Agent memory usage: WSS=3256320 PFU=150257664
[Wed Jan 20 15:12:07 2021][info] running task Maintenance
[Wed Jan 20 15:12:11 2021][info] FusionInventory Agent memory usage: WSS=4026368 PFU=149975040

**Comment by nbriche** [comment]
Same versions, same problem.

This is due to a typo in [agent.class.php#L1045](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/62e8e5b1c2746056e178fa7e40ab033d04a92df7/inc/agent.class.php#L1045).

It tries to instanciate DomainItem, should be Domain_Item. Adding the underscore corrects the bug.

**Comment by nbriche** [comment]
Seems corrected in the current branch, actually.

**Comment by Sergh71** [comment]
Replaced.It didn't work. A new inscription has appeared, but when pressed, it only blinks and then again it is proposed to click on it. No inventory and rollout.
![image](https://user-images.githubusercontent.com/77730253/106707788-dd146080-6602-11eb-8a64-2e2f7a61ff76.png)

**Comment by Sergh71** [comment]
Replaced. Remote inventory is working. Remote deployment still doesn't work.
![image](https://user-images.githubusercontent.com/77730253/106714045-55cbea80-660c-11eb-9b83-d1ed73a3911b.png)
log from agent
[Wed Feb  3 10:38:18 2021][info] No Collect job enabled or Collect support disabled server side.
[Wed Feb  3 10:38:20 2021][debug] [http server] GET request /status from client 10.168.70.59
[Wed Feb  3 10:38:20 2021][debug] [http server] response status 200
[Wed Feb  3 10:38:20 2021][debug] Agent memory usage before freeing memory: WSS=328421376 PFU=579670016
[Wed Feb  3 10:38:20 2021][info] FusionInventory Agent memory usage: WSS=3031040 PFU=579670016
[Wed Feb  3 10:38:22 2021][debug] [http server] GET request /status from client 10.168.70.59
[Wed Feb  3 10:38:22 2021][debug] new thread 6067 to handle task Maintenance
[Wed Feb  3 10:38:22 2021][debug] [http server] response status 200
[Wed Feb  3 10:38:22 2021][info] running task Maintenance
[Wed Feb  3 10:38:22 2021][debug2] Doing Deploy Maintenance
[Wed Feb  3 10:38:24 2021][debug] [http server] GET request /status from client 10.168.70.59
[Wed Feb  3 10:38:24 2021][debug] [http server] response status 200
[Wed Feb  3 10:38:24 2021][debug] Agent memory usage before freeing memory: WSS=286408704 PFU=579670016
[Wed Feb  3 10:38:24 2021][info] FusionInventory Agent memory usage: WSS=3014656 PFU=579670016
[Wed Feb  3 10:38:24 2021][debug] [http server] GET request /status from client 10.168.70.59
[Wed Feb  3 10:38:24 2021][debug] [http server] response status 200

**Comment by ddurieux** [comment]
You have changed the url of your GLPI (or the IP) between the 2 versions of GLPI

**Comment by g-bougard** [comment]
And so don't forget do check the FusionInventory URL in Entity Administration: for each entity, there's a FusionInventory dedicated page where you set the GLPI server URL. This is this URL which is used by the Deploy task as provided by the server. If it is wrong, nothing will happen on the agent side.

**Comment by Sergh71** [comment]
Yes, sorry I have 2 GLPI servers. 2 is the same problem.
log from agent where remote deployment does not work:

[Wed Feb  3 11:36:29 2021][info] FusionInventory Agent service starting
[Wed Feb  3 11:36:30 2021][info] [http server] HTTPD service started on port 62354
[Wed Feb  3 11:36:35 2021][info] FusionInventory Agent memory usage: WSS=3571712 PFU=97873920
[Wed Feb  3 11:37:05 2021][info] running task Maintenance
[Wed Feb  3 11:37:09 2021][info] FusionInventory Agent memory usage: WSS=3051520 PFU=104763392
[Wed Feb  3 11:38:53 2021][info] target server0: server https://172.16.104.223/plugins/fusioninventory
[Wed Feb  3 11:38:53 2021][info] sending prolog request to server0
[Wed Feb  3 11:38:54 2021][info] running task Deploy
[Wed Feb  3 11:38:55 2021][error] [http client] Can't decode JSON content, starting with <!DOCTYPE html>
[Wed Feb  3 11:38:55 2021][info] No Deploy job found in server jobs list.
[Wed Feb  3 11:38:58 2021][info] running task ESX
[Wed Feb  3 11:38:58 2021][info] No ESX job enabled or ESX support disabled server side.
[Wed Feb  3 11:39:08 2021][info] running task Inventory
[Wed Feb  3 11:39:08 2021][info] New inventory from ws3.tech.local-2021-01-20-12-47-03 for server0
[Wed Feb  3 11:41:03 2021][info] running task Collect
[Wed Feb  3 11:41:03 2021][info] No Collect job enabled or Collect support disabled server side.
[Wed Feb  3 11:41:07 2021][info] FusionInventory Agent memory usage: WSS=3366912 PFU=138186752
[Wed Feb  3 11:41:09 2021][info] running task Maintenance
[Wed Feb  3 11:41:13 2021][info] FusionInventory Agent memory usage: WSS=3940352 PFU=137969664
[Wed Feb  3 11:43:02 2021][info] running task Maintenance
[Wed Feb  3 11:43:06 2021][info] FusionInventory Agent memory usage: WSS=3248128 PFU=136933376
[Wed Feb  3 11:45:03 2021][info] running task Maintenance
[Wed Feb  3 11:45:07 2021][info] FusionInventory Agent memory usage: WSS=3268608 PFU=138047488
[Wed Feb  3 11:46:56 2021][info] running task Maintenance
[Wed Feb  3 11:47:00 2021][info] FusionInventory Agent memory usage: WSS=3174400 PFU=149729280
[Wed Feb  3 11:48:54 2021][info] running task Maintenance
[Wed Feb  3 11:49:00 2021][info] FusionInventory Agent memory usage: WSS=3907584 PFU=136757248

**Comment by ddurieux** [comment]
The server URL seems wrong, it must be `https://172.16.104.223/plugins/fusioninventory/`, don't forget the `/` at the end

**Comment by Sergh71** [comment]
Fixed, but remote deployment still doesn't work:

[Wed Feb  3 12:10:28 2021][info] running task Inventory
[Wed Feb  3 12:10:28 2021][info] New inventory from ws3.tech.local-2021-01-20-12-47-03 for server0
[Wed Feb  3 12:12:21 2021][info] running task Collect
[Wed Feb  3 12:12:21 2021][info] No Collect job enabled or Collect support disabled server side.
[Wed Feb  3 12:12:25 2021][info] FusionInventory Agent memory usage: WSS=3186688 PFU=148152320
[Wed Feb  3 12:12:27 2021][info] running task Maintenance
[Wed Feb  3 12:12:31 2021][info] FusionInventory Agent memory usage: WSS=4014080 PFU=148701184
[Wed Feb  3 12:12:46 2021][info] FusionInventory Agent exiting (2232)
[Wed Feb  3 12:12:56 2021][info] FusionInventory Agent service starting
[Wed Feb  3 12:12:58 2021][info] [http server] HTTPD service started on port 62354
[Wed Feb  3 12:13:00 2021][info] FusionInventory Agent memory usage: WSS=3600384 PFU=98004992
[Wed Feb  3 12:13:08 2021][info] target server0: server https://172.16.104.223/plugins/fusioninventory/
[Wed Feb  3 12:13:09 2021][info] sending prolog request to server0
[Wed Feb  3 12:13:09 2021][info] running task Collect
[Wed Feb  3 12:13:10 2021][info] No Collect job enabled or Collect support disabled server side.
[Wed Feb  3 12:13:14 2021][info] running task ESX
[Wed Feb  3 12:13:14 2021][info] No ESX job enabled or ESX support disabled server side.
[Wed Feb  3 12:13:17 2021][info] running task Inventory
[Wed Feb  3 12:13:17 2021][info] New inventory from ws3.tech.local-2021-01-20-12-47-03 for server0
[Wed Feb  3 12:15:02 2021][info] running task Deploy
[Wed Feb  3 12:15:03 2021][error] [http client] Can't decode JSON content, starting with <!DOCTYPE html>
[Wed Feb  3 12:15:03 2021][info] No Deploy job found in server jobs list.
[Wed Feb  3 12:15:15 2021][info] FusionInventory Agent memory usage: WSS=3342336 PFU=141869056
[Wed Feb  3 12:15:17 2021][info] running task Maintenance
[Wed Feb  3 12:15:22 2021][info] FusionInventory Agent memory usage: WSS=3244032 PFU=142745600

**Comment by ddurieux** [comment]
Can you run the agent in debug please ?

**Comment by Sergh71** [comment]
[fusioninventory-agent.log](https://github.com/fusioninventory/fusioninventory-for-glpi/files/5917373/fusioninventory-agent.log)

**Comment by ddurieux** [comment]
and in debug=2? (sorry, not enough in debug=1)

**Comment by Sergh71** [comment]
No problem, thanks for helping!
[fusioninventory-agent.log](https://github.com/fusioninventory/fusioninventory-for-glpi/files/5917456/fusioninventory-agent.log)

**Comment by ddurieux** [comment]
Seems the URL for deploy not right.
I must check it in 9.5 version (I use 9.4 version for the moment)

**Comment by g-bougard** [comment]
```
[Wed Feb  3 12:43:31 2021][info] running task Deploy
[Wed Feb  3 12:43:31 2021][debug2] https://172.16.104.223/plugins/fusioninventory/?action=getConfig&task[Deploy]=2.8&machineid=ws3.tech.local-2021-01-20-12-47-03
[Wed Feb  3 12:43:31 2021][debug2] https://172.16.104.223/ajax/marketplace.php/plugins/fusioninventory/b/deploy/?action=getJobs&machineid=ws3.tech.local-2021-01-20-12-47-03&version=2.8
[Wed Feb  3 12:43:31 2021][error] [http client] Can't decode JSON content, starting with <!DOCTYPE html>
[Wed Feb  3 12:43:31 2021][debug] bad JSON: No answer from server.
```
First URL seems right, but the second seems to come from a server redirection sent back to the agent in place of the expected Deploy jobs configuration.

**Comment by g-bougard** [comment]
Did you check the URL in FusionInventory page of your entity in related Entity Administration page as I asked you before ?

**Comment by ddurieux** [comment]
Don't use marketplace please, it's a security hole
Install the plugin manually, see http://fusioninventory.org/documentation/fi4g/installation.html

**Comment by Sergh71** [comment]
> Did you check the URL in FusionInventory page of your entity in related Entity Administration page as I asked you before ?
Do you mean that?
![image](https://user-images.githubusercontent.com/77730253/106731758-f1675600-6620-11eb-8d4b-6a2a1adf3bad.png)

**Comment by g-bougard** [comment]
No I mean in your GLPI administration page.

**Comment by Sergh71** [comment]
> Don't use marketplace please, it's a security hole
> Install the plugin manually, see http://fusioninventory.org/documentation/fi4g/installation.html


I have not used the marketplace. I installed manually from github

**Comment by Sergh71** [comment]
> No I mean in your GLPI administration page.

Sorry, I don't really understand where to look, here?
![image](https://user-images.githubusercontent.com/77730253/106732350-a7cb3b00-6621-11eb-8f65-da23df0f0f86.png)

**Comment by ddurieux** [comment]
In Configuration > entity, in root entity you have a tab _FusionInventory_ where you canconfigure the URL

**Comment by g-bougard** [comment]
![image](https://user-images.githubusercontent.com/12514489/106732932-9417d880-6611-11eb-898e-e7de813d703e.png)

**Comment by Sergh71** [comment]
![image](https://user-images.githubusercontent.com/77730253/106733258-b9611280-6622-11eb-8ee0-714ffc3d4b42.png)

**Comment by ddurieux** [comment]
remove the `ajax/marketplace/` in the URL

**Comment by g-bougard** [comment]
@Sergh71 I confirm, this URL is wrong and I think it should be `https://172.16.104.223/` in your case. Did you set it manually ?
Check then the log and in the case you see it missed `/plugin/fusioninventory/`, add it.

**Comment by Sergh71** [comment]
Hooray! It worked! Thanks a lot!

**Comment by Sergh71** [comment]
> @Sergh71 I confirm, this URL is wrong and I think it should be `https://172.16.104.223/` in your case. Did you set it manually ?
> Check then the log and in the case you see it missed `/plugin/fusioninventory/`, add it.


I did not change this line, it was already there.

**Comment by Sergh71** [comment]
g-bougard and ddurieux!
Thank you very much, guys, and may everything be fine with you!
