### ISSUE TITLE
Package interface incompleted

### ISSUE THREAD

**Issue by ITSupport-Ponant** [fusioninventory/fusioninventory-for-glpi#3133]
Hello,

When opening an existing package, the interface is incomplete.
The whole package definition is missing (script, file, ....)

Best regards,

**Comment by ddurieux** [comment]
Fixed in #3122

**Comment by ITSupport-Ponant** [comment]
Sorry but it still does not work with the file deploypackage.class.php corrected ...

**Comment by ddurieux** [comment]
That's strange, it's fixed for me and tested by many users

**Comment by ITSupport-Ponant** [comment]
Hello David,

Yes, that's strange ... I deleted and created the file but ... same result ...
![2021-03-21_20h31_27](https://user-images.githubusercontent.com/60793499/111918243-7baa3300-8a84-11eb-8081-17eacd92d786.png)

How can I download all latest files ?

**Comment by ddurieux** [comment]
created? updated you mean?

**Comment by ITSupport-Ponant** [comment]
I created an new file with same name and pasted all code found here : https://github.com/fusioninventory/fusioninventory-for-glpi/blob/4d7b2344d25cdd5e78845cfc38a517f2bf9f10e0/inc/deploypackage.class.php

**Comment by ddurieux** [comment]
I release 9.5+3.0 few seconds ago, try update to sse if you have always the problem ;)

**Comment by ITSupport-Ponant** [comment]
David,

C'est bcp mieux ! Perfect !

Il ne me reste plus qu'à me débarrasser de ce message : 
![2021-03-21_21h10_45](https://user-images.githubusercontent.com/60793499/111919405-22450280-8a8a-11eb-905c-167b79b3889f.png)

**Comment by ITSupport-Ponant** [comment]
Corrected too.
Thanks a lot and very good job 👍

**Comment by ddurieux** [comment]
^_^
